"""Generated facts — docs/state/FACTS.json + NOW.md (MEMORY_SCHEMA.md §9).

Deterministic: given the same repo HEAD and environment inputs, regeneration
produces byte-identical output. ``generated_at`` is anchored to the HEAD commit
date (a reproducible source event), not the wall clock. Test evidence is only
recorded after a real run — nothing is inferred from Markdown.

Commands:
    python -m tools.memoryctl facts           # write FACTS.json + NOW.md
    python -m tools.memoryctl facts --check   # verify freshness/equality, no writes
"""

from __future__ import annotations

import contextlib
import hashlib
import json
import os
import subprocess
import tempfile
from pathlib import Path

GENERATOR_VERSION = "0.1.0"
SCHEMA_VERSION = "memory/v2alpha1"


def _run(cmd: list[str], cwd: Path, timeout: int = 30) -> tuple[int, str]:
    try:
        proc = subprocess.run(
            cmd,
            cwd=str(cwd),
            capture_output=True,
            text=True,
            timeout=timeout,
            env={**os.environ, "PYTHONIOENCODING": "utf-8"},
        )
        return proc.returncode, proc.stdout.strip()
    except (OSError, subprocess.TimeoutExpired) as exc:  # pragma: no cover - env dependent
        return 127, str(exc)


def git_head(root: Path) -> str | None:
    """Anchor: the last commit that did NOT touch docs/state (generated files).

    The manifest must not chase its own commit: committing the generated
    docs/state must not change the recorded head, otherwise regeneration is
    never stable. A real source commit (code/docs) advances the anchor.
    """
    code, out = _run(
        ["git", "log", "-1", "--format=%H", "HEAD", "--", ".", ":(exclude)docs/state"],
        root,
    )
    return out if code == 0 and len(out) == 40 else None


def git_branch(root: Path) -> str | None:
    code, out = _run(["git", "rev-parse", "--abbrev-ref", "HEAD"], root)
    if code != 0:
        return None
    return out or None


def git_dirty(root: Path) -> bool:
    code, out = _run(["git", "status", "--porcelain"], root)
    return code == 0 and bool(out)


def git_diff_hash(root: Path) -> str | None:
    code, out = _run(["git", "diff", "--no-color"], root)
    if code != 0 or not out:
        return None
    return "sha256:" + hashlib.sha256(out.encode("utf-8")).hexdigest()


def git_head_date(root: Path) -> str | None:
    """Commit date of the source anchor (same commit as git_head)."""
    code, out = _run(
        ["git", "log", "-1", "--format=%cI", "HEAD", "--", ".", ":(exclude)docs/state"],
        root,
    )
    return out if code == 0 else None


def git_repository(root: Path) -> str:
    code, out = _run(["git", "config", "--get", "remote.origin.url"], root)
    if code == 0 and out:
        url = out.rstrip("/")
        if url.endswith(".git"):
            url = url[:-4]
        for prefix in ("https://github.com/", "git@github.com:", "git@gitlab.com:"):
            if url.startswith(prefix):
                return url[len(prefix) :]
        return url.rsplit("/", 1)[-1] if "/" in url else url
    return root.name


def alembic_heads(root: Path) -> dict:
    """Run `alembic heads` and record output; never asserts success."""
    code, out = _run(["alembic", "heads"], root)
    if code != 0:
        return {"heads": [], "command": "alembic heads", "checked_at": None}
    heads = [line.split()[0].strip() for line in out.splitlines() if line.strip()]
    # reproducible timestamp anchor = HEAD commit date, not wall clock
    return {"heads": heads, "command": "alembic heads", "checked_at": git_head_date(root)}


def collect_facts(root: Path) -> dict:
    head = git_head(root)
    dirty = git_dirty(root)
    facts = {
        "schema_version": SCHEMA_VERSION,
        "kind": "fact_manifest",
        "repository": git_repository(root),
        "generated_at": git_head_date(root),
        "generator_version": GENERATOR_VERSION,
        "git": {
            "head": head,
            "branch": git_branch(root),
            "dirty": dirty,
            "diff_hash": git_diff_hash(root) if dirty else None,
        },
        "alembic": alembic_heads(root),
        "tests": [],
        "ci": [],
        "artifacts": [],
    }
    return facts


def render_now(facts: dict) -> str:
    git = facts["git"]
    head = git.get("head") or "unknown"
    lines = [
        "# NOW — снимок текущего состояния (generated)",
        "",
        "<!-- GENERATED by memoryctl facts v{} — do not edit. Source: docs/state/FACTS.json -->".format(
            facts.get("generator_version", GENERATOR_VERSION)
        ),
        "",
        f"- **HEAD**: `{head[:12]}` ({head})",
        f"- **Branch**: {git.get('branch') or 'detached'}",
        f"- **Dirty**: {'yes' if git.get('dirty') else 'no'}",
        f"- **Generated at (source)**: {facts.get('generated_at') or '—'}",
        f"- **Repository**: {facts.get('repository') or '—'}",
    ]
    alembic = facts.get("alembic") or {}
    heads = alembic.get("heads") or []
    lines.append(f"- **Alembic heads**: {len(heads)} ({', '.join(h[:8] for h in heads) if heads else 'not checked'})")
    tests = facts.get("tests") or []
    if tests:
        last = tests[-1]
        lines.append(
            f"- **Last test run**: {last.get('passed')} passed / {last.get('failed')} failed ({last.get('command')})"
        )
    else:
        lines.append("- **Last test run**: not recorded (no real run in this manifest)")
    lines.append("")
    lines.append("> Факт подтверждает только сам manifest и его `head`. Любое использование этого")
    lines.append("> снимка при другом HEAD делает его stale — перегенерируйте через `memoryctl facts`.")
    lines.append("")
    return "\n".join(lines)


def write_facts(root: Path, facts: dict) -> tuple[Path, Path]:
    state_dir = root / "docs" / "state"
    state_dir.mkdir(parents=True, exist_ok=True)
    json_path = state_dir / "FACTS.json"
    now_path = state_dir / "NOW.md"
    payload = json.dumps(facts, indent=2, ensure_ascii=False, sort_keys=True) + "\n"
    now = render_now(facts)
    _atomic_write(json_path, payload)
    _atomic_write(now_path, now)
    return json_path, now_path


def _atomic_write(path: Path, content: str) -> None:
    fd, tmp = tempfile.mkstemp(dir=str(path.parent), prefix=".tmp-", suffix=".new")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(content)
        os.replace(tmp, path)
    except BaseException:
        with contextlib.suppress(OSError):
            os.unlink(tmp)
        raise


def _normalize_for_check(facts: dict) -> dict:
    """Drop volatile fields (dirty flag, diff hash) before comparing freshness.

    In-progress edits must not invalidate a manifest anchored to the same HEAD;
    freshness is decided by the source anchor (git.head) alone.
    """
    normalized = {k: (dict(v) if isinstance(v, dict) else v) for k, v in facts.items()}
    git = normalized.get("git")
    if isinstance(git, dict):
        git.pop("dirty", None)
        git.pop("diff_hash", None)
    return normalized


def check_facts(root: Path) -> tuple[bool, str]:
    """Verify FACTS.json is fresh (source anchor == current) and deterministic."""
    json_path = root / "docs" / "state" / "FACTS.json"
    if not json_path.exists():
        return False, "docs/state/FACTS.json missing — run 'memoryctl facts'"
    current = collect_facts(root)
    try:
        stored = json.loads(json_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        return False, f"FACTS.json is not valid JSON: {exc}"
    if stored.get("git", {}).get("head") != current["git"].get("head"):
        return (
            False,
            f"stale: FACTS.json HEAD={stored.get('git', {}).get('head')} != current HEAD={current['git'].get('head')}",
        )
    expected = json.dumps(_normalize_for_check(current), indent=2, ensure_ascii=False, sort_keys=True) + "\n"
    actual = json.dumps(_normalize_for_check(stored), indent=2, ensure_ascii=False, sort_keys=True) + "\n"
    if actual != expected:
        return False, "FACTS.json is not deterministic for current HEAD — regenerate with 'memoryctl facts'"
    return True, "FACTS.json fresh and deterministic"
