"""Database Model for Automation Trigger Engine with AI Agent Auto-Generation."""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import Boolean, DateTime, Float, ForeignKey, String, Text, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.models import Base


class AutomationTrigger(Base):
    """Automated trigger rule set manually or generated by AI Agent from user history."""

    __tablename__ = "automation_triggers"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )

    condition_type: Mapped[str] = mapped_column(
        String(50), nullable=False
    )  # missed_tasks_count / high_stress_score / streak_broken
    threshold_value: Mapped[float] = mapped_column(Float, default=2.0)

    action_type: Mapped[str] = mapped_column(
        String(50), nullable=False
    )  # increase_strictness / apply_penalty / generate_emergency_quest
    action_params: Mapped[str | None] = mapped_column(Text, nullable=True)  # JSON string

    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    is_agent_generated: Mapped[bool] = mapped_column(Boolean, default=False)
    reasoning_notes: Mapped[str | None] = mapped_column(Text, nullable=True)

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now(), nullable=False)

    def __repr__(self) -> str:
        return f"<AutomationTrigger(id={self.id}, condition={self.condition_type}, action={self.action_type})>"
