"""Unit tests for tools.memoryctl.lint."""

from __future__ import annotations

import json
import subprocess

from tools.memoryctl import facts
from tools.memoryctl.lint import lint

VALID_KNOWLEDGE = """---
schema_version: memory/v2alpha1
id: K-TEST-PAGE
kind: knowledge
title: Test page
status: active
authority: derived
owners:
  - project-owner
scope:
  - test
source_refs:
  - path: DOCUMENTATION_MAP.md
    relation: defines
last_verified_at: 2026-08-13T00:00:00Z
last_verified_commit: 0000000000000000000000000000000000000000
review_on: source-change
---
# Test
"""


def _setup(root, *, head_override: str | None = None, now_banner: bool = True) -> str:
    root.mkdir(parents=True, exist_ok=True)
    (root / "DOCUMENTATION_MAP.md").write_text("# Map\n", encoding="utf-8")
    # minimal git repo
    subprocess.run(["git", "init", "-q"], cwd=str(root), capture_output=True, timeout=30)
    subprocess.run(
        ["git", "-c", "user.email=t@e.com", "-c", "user.name=T", "add", "-A"],
        cwd=str(root),
        capture_output=True,
        timeout=30,
    )
    subprocess.run(
        ["git", "-c", "user.email=t@e.com", "-c", "user.name=T", "commit", "-qm", "init"],
        cwd=str(root),
        capture_output=True,
        timeout=30,
    )
    head = subprocess.run(
        ["git", "rev-parse", "HEAD"], cwd=str(root), capture_output=True, text=True, timeout=30
    ).stdout.strip()
    f = facts.collect_facts(root)
    f["git"]["head"] = head_override or head
    facts.write_facts(root, f)
    (root / "docs" / "state" / "NOW.md").write_text(
        "# NOW\n\n<!-- GENERATED by memoryctl facts v0.1.0 — do not edit -->\n\n- HEAD: x\n",
        encoding="utf-8",
    ) if now_banner else (root / "docs" / "state" / "NOW.md").write_text("# NOW\n", encoding="utf-8")
    return head


def test_valid_corpus_passes(tmp_path):
    _setup(tmp_path)
    (tmp_path / "docs" / "wiki").mkdir(parents=True)
    page = tmp_path / "docs" / "wiki" / "safety.md"
    page.write_text(
        VALID_KNOWLEDGE.replace("0000000000000000000000000000000000000000", _setup_head(tmp_path)), encoding="utf-8"
    )
    result = lint(tmp_path)
    assert not result.has_errors, [str(i) for i in result.issues]


def _setup_head(tmp_path) -> str:
    return subprocess.run(
        ["git", "rev-parse", "HEAD"], cwd=str(tmp_path), capture_output=True, text=True, timeout=30
    ).stdout.strip()


def test_duplicate_id_error(tmp_path):
    _setup(tmp_path)
    head = _setup_head(tmp_path)
    (tmp_path / "docs" / "wiki").mkdir(parents=True)
    (tmp_path / "docs" / "wiki" / "a.md").write_text(
        VALID_KNOWLEDGE.replace("0000000000000000000000000000000000000000", head), encoding="utf-8"
    )
    (tmp_path / "docs" / "wiki" / "b.md").write_text(
        VALID_KNOWLEDGE.replace("0000000000000000000000000000000000000000", head).replace("# Test", "# Test 2"),
        encoding="utf-8",
    )
    result = lint(tmp_path)
    assert any("duplicate id" in i.message for i in result.issues if i.level == "error")


def test_secret_pattern_detected(tmp_path):
    head = _setup(tmp_path)
    (tmp_path / "docs" / "wiki").mkdir(parents=True)
    text = VALID_KNOWLEDGE.replace("0000000000000000000000000000000000000000", head)
    text += '\napi_key = "sk-ABCDEFGHIJKLMNOPQRSTUVWXYZ123456"\n'
    (tmp_path / "docs" / "wiki" / "secret.md").write_text(text, encoding="utf-8")
    result = lint(tmp_path)
    assert any("secret/credential" in i.message for i in result.issues if i.level == "error")


def test_stale_facts_error(tmp_path):
    _setup(tmp_path, head_override="a" * 40)
    result = lint(tmp_path)
    assert any("stale" in i.message for i in result.issues if i.level == "error")


def test_now_banner_required(tmp_path):
    _setup(tmp_path, now_banner=False)
    result = lint(tmp_path)
    assert any("generated banner" in i.message for i in result.issues if i.level == "error")


def test_denied_tracked_file_warning(tmp_path):
    _setup(tmp_path)
    (tmp_path / ".env.prod").write_text("SECRET=1\n", encoding="utf-8")
    subprocess.run(["git", "add", "-A"], cwd=str(tmp_path), capture_output=True, timeout=30)
    result = lint(tmp_path)
    assert any("suspected secret" in i.message and i.level == "warning" for i in result.issues)


def test_allowlisted_tracked_files_not_warned(tmp_path):
    _setup(tmp_path)
    (tmp_path / ".env.example").write_text("POSTGRES_USER=tracker\n", encoding="utf-8")
    fonts = tmp_path / "app" / "static" / "fonts"
    fonts.mkdir(parents=True)
    (fonts / "Inter.woff2").write_bytes(b"\x00\x01")
    subprocess.run(["git", "add", "-A"], cwd=str(tmp_path), capture_output=True, timeout=30)
    result = lint(tmp_path)
    assert not any("denylist" in i.message for i in result.issues)


def test_invalid_sha_in_facts(tmp_path):
    _setup(tmp_path)
    p = tmp_path / "docs" / "state" / "FACTS.json"
    data = json.loads(p.read_text(encoding="utf-8"))
    data["git"]["head"] = "abc"
    p.write_text(json.dumps(data, indent=2), encoding="utf-8")
    result = lint(tmp_path)
    assert any("not a full SHA" in i.message for i in result.issues if i.level == "error")
