"""Unit tests for tools.memoryctl.facts (generated fact manifest)."""

from __future__ import annotations

import json
import subprocess

from tools.memoryctl import facts


def _commit_all(root, message: str) -> None:
    subprocess.run(["git", "add", "-A"], cwd=str(root), capture_output=True, text=True, timeout=30)
    proc = subprocess.run(
        ["git", "-c", "user.email=test@example.com", "-c", "user.name=Test", "commit", "-qm", message],
        cwd=str(root),
        capture_output=True,
        text=True,
        timeout=30,
    )
    assert proc.returncode == 0, proc.stderr


def make_git_repo(root, filename: str = "file.txt", content: str = "hello\n") -> str:
    """Init a git repo with one commit; returns the full HEAD sha."""
    root.mkdir(parents=True, exist_ok=True)
    (root / filename).write_text(content, encoding="utf-8")
    subprocess.run(["git", "init", "-q"], cwd=str(root), capture_output=True, text=True, timeout=30)
    _commit_all(root, "init")
    proc = subprocess.run(["git", "rev-parse", "HEAD"], cwd=str(root), capture_output=True, text=True, timeout=30)
    return proc.stdout.strip()


def test_git_head_is_full_sha(tmp_path):
    head = make_git_repo(tmp_path)
    assert facts.git_head(tmp_path) == head
    assert len(head) == 40


def test_collect_facts_shape(tmp_path):
    head = make_git_repo(tmp_path)
    f = facts.collect_facts(tmp_path)
    assert f["kind"] == "fact_manifest"
    assert f["schema_version"] == "memory/v2alpha1"
    assert f["git"]["head"] == head
    assert f["git"]["dirty"] is False
    assert f["git"]["diff_hash"] is None
    assert f["generated_at"] is not None
    assert f["tests"] == []  # no test evidence without a real run
    assert f["alembic"]["command"] == "alembic heads"


def test_dirty_state_reflected(tmp_path):
    make_git_repo(tmp_path)
    (tmp_path / "file.txt").write_text("changed\n", encoding="utf-8")
    f = facts.collect_facts(tmp_path)
    assert f["git"]["dirty"] is True
    assert f["git"]["diff_hash"] is not None
    assert f["git"]["diff_hash"].startswith("sha256:")


def test_alembic_failure_falls_back_to_empty(tmp_path):
    make_git_repo(tmp_path)  # no alembic.ini in tmp dir -> alembic heads fails
    a = facts.alembic_heads(tmp_path)
    assert a["heads"] == []
    assert a["checked_at"] is None
    assert a["command"] == "alembic heads"


def test_generation_is_deterministic(tmp_path):
    make_git_repo(tmp_path)
    f1 = facts.collect_facts(tmp_path)
    assert facts.collect_facts(tmp_path) == f1
    json_path, now_path = facts.write_facts(tmp_path, f1)
    first_json = json_path.read_text(encoding="utf-8")
    first_now = now_path.read_text(encoding="utf-8")
    # idempotent for the same payload
    json_path2, now_path2 = facts.write_facts(tmp_path, f1)
    assert json_path2.read_text(encoding="utf-8") == first_json
    assert now_path2.read_text(encoding="utf-8") == first_now
    # deterministic after committing the generated files (clean tree)
    _commit_all(tmp_path, "facts")
    f2 = facts.collect_facts(tmp_path)
    assert f2 == f1
    json_path3, _ = facts.write_facts(tmp_path, f2)
    assert json_path3.read_text(encoding="utf-8") == first_json


def test_check_facts_fresh(tmp_path):
    make_git_repo(tmp_path)
    facts.write_facts(tmp_path, facts.collect_facts(tmp_path))
    _commit_all(tmp_path, "facts")
    ok, msg = facts.check_facts(tmp_path)
    assert ok, msg


def test_check_facts_stale_after_new_commit(tmp_path):
    make_git_repo(tmp_path)
    facts.write_facts(tmp_path, facts.collect_facts(tmp_path))
    (tmp_path / "file.txt").write_text("v2\n", encoding="utf-8")
    subprocess.run(
        ["git", "-c", "user.email=test@example.com", "-c", "user.name=Test", "commit", "-qam", "second"],
        cwd=str(tmp_path),
        capture_output=True,
        text=True,
        timeout=30,
    )
    ok, msg = facts.check_facts(tmp_path)
    assert not ok
    assert "stale" in msg


def test_check_facts_missing_file(tmp_path):
    ok, msg = facts.check_facts(tmp_path)
    assert not ok
    assert "missing" in msg


def test_facts_json_parses(tmp_path):
    make_git_repo(tmp_path)
    facts.write_facts(tmp_path, facts.collect_facts(tmp_path))
    stored = json.loads((tmp_path / "docs" / "state" / "FACTS.json").read_text(encoding="utf-8"))
    assert stored["kind"] == "fact_manifest"
    assert len(stored["git"]["head"]) == 40


def test_now_has_generated_banner(tmp_path):
    make_git_repo(tmp_path)
    facts.write_facts(tmp_path, facts.collect_facts(tmp_path))
    now = (tmp_path / "docs" / "state" / "NOW.md").read_text(encoding="utf-8")
    assert "GENERATED by memoryctl facts" in now
    assert "HEAD" in now
